name: Build and Test

on:
    push:
        branches:
            - main
    pull_request:
        branches:
            - main

jobs:
    build-and-test:
        runs-on: ubuntu-latest

        steps:
          - name: Checkout code
            uses: actions/checkout@v3

          - name: Install podman
            run: sudo apt install podman -y

          - name: Set up shell script permissions
            run: chmod +x ./slurm_build.sh
 
          - name: Disable podman remove
            run: |
                sudo sed -i 's/podman images/#podman images/g' ./slurm_build.sh
                
          - name: Run shell script
            run: ./slurm_build.sh
  
          - name: Run validation compilation
            run: |
                pkgs=$(ls -1 ./rpmbuild/RPMS/x86_64/slurm-* | wc -l)
                if [ $pkgs -eq 0 ]; then
                    echo "No packages found in ./rpmbuild/RPMS/x86_64"
                    exit 1
                else
                    echo "Packages found in ./rpmbuild/RPMS/x86_64"
                    echo "Packages: in ./rpmbuild/RPMS/x86_64 $pkgs" 
                fi


